name: Publish

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Generate README.md
      uses: actions-js/profile-readme@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        username: WelissonLuca
        template: "TEMPLATE.md"
      
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
